FROM fedora:42

RUN dnf -y update && \
    dnf -y install git meson gcc glib2-devel ncurses-devel perl-ExtUtils-Embed  
RUN git clone https://github.com/irssi/irssi.git
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build