FROM rust:1.75-slim

RUN apt-get update && apt-get install -y \
    git

WORKDIR /usr/src
RUN git clone --recursive https://github.com/sharkdp/bat
WORKDIR /usr/src/bat
RUN cargo install --path . --locked