FROM build-irssi:latest

RUN apt-get update && \
    apt-get install -y dh-make debhelper devscripts

WORKDIR /build

RUN mv /build/irssi /build/irssi-1.0.0

WORKDIR /build/irssi-1.0.0

COPY build.sh .

RUN chmod +x build.sh

CMD ["./build.sh"]