pipeline {
    agent any

    environment {
        DOCKER_BUILDKIT = 1
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'MN417158',
                    url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    def dockerfilePath = 'INO/GCL02/MN417158/Sprawozdanie2/Dockerfilechalk.build'

                    def image = docker.build("bldr", "-f ${dockerfilePath} .")
                }
            }
        }
        stage('Deploy') {
             steps {
                script {
                    def buildContext = 'INO/GCL02/MN417158/Sprawozdanie2'

                    sh """
                        docker run --rm -v \$PWD/${buildContext}:/output bldr \
                        cp -r /chalk/node_modules /output/
                    """


                    writeFile file: "${buildContext}/demo.js", text: '''
                        import chalk from 'chalk';
                        const name = 'Sindre';
                        console.log(chalk.green('Hello %s'), name);
                    '''.stripIndent()

                    def deployImage = docker.build("deploy", "-f ${buildContext}/Dockerfilechalk.deploy ${buildContext}")

                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    def output = sh(script: "docker run --rm deploy", returnStdout: true).trim()
                    echo "Wynik działania demo.js:\n${output}"
                }
            }       
        }


    }
}

