FROM fedora:latest

WORKDIR /app

COPY artifacts/ /app/

COPY artifacts/redis-server-* /app/redis-server
COPY artifacts/redis-cli-* /app/redis-cli

RUN ls -l /app/artifacts

RUN chmod +x /app/redis-server /app/redis-cli

EXPOSE 6379

CMD ["./redis-server", "--port", "6379"]
