FROM fedora:latest

RUN dnf install -y gcc-c++ make tcl git openssl-devel systemd-devel curl procps-ng && dnf clean all

RUN git clone https://github.com/redis/redis.git /redis

WORKDIR /redis

RUN make

RUN cp /redis/src/redis-server /redis/redis-server
RUN cp /redis/src/redis-cli /redis/redis-cli
