FROM fedora:41

RUN dnf -y update && \
    dnf clean all

RUN useradd -m appuser

COPY --from=sqlite-build /sqlite/sqlite3 /sqlite/sqlite3

COPY smoke-test.sh /smoke-test.sh
RUN chmod +x /sqlite/sqlite3 /smoke-test.sh

USER appuser

CMD ["./smoke-test.sh"]