pipeline {
    agent any

    environment {
        DOCKER_BUILDKIT = 1
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'MN417158',
                    url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    	def shortCommit = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    	def date = sh(script: "date +%Y%m%d%H%M%S", returnStdout: true).trim()
                    	env.IMAGE_VERSION = "${date}-${shortCommit}"
                    	echo "Wersja obrazu: ${env.IMAGE_VERSION}"

			def dockerfilePath = 'INO/GCL02/MN417158/Sprawozdanie2/Dockerfilechalk.build'

                    	def image = docker.build("bldr", "-f ${dockerfilePath} .")
                }
            }
        }
	stage('Test') {
            steps {
                script {
                    def dockerfilePath = 'INO/GCL02/MN417158/Sprawozdanie2/Dockerfilechalk.test'

                    def image = docker.build("test:${env.IMAGE_VERSION}", "-f ${dockerfilePath} .")
                }
            }
        }
        stage('Deploy') {
             steps {
                script {
                    def buildContext = 'INO/GCL02/MN417158/Sprawozdanie2'

                    sh """
                        docker run --rm -v \$PWD/${buildContext}:/output bldr:${env.IMAGE_VERSION} \
                        cp -r /chalk/node_modules /output/
                    """


                    writeFile file: "${buildContext}/demo.js", text: '''
                        import chalk from 'chalk';
                        const name = 'Sindre';
                        console.log(chalk.green('Hello %s'), name);
                    '''.stripIndent()

                    def deployImage = docker.build("deploy:${env.IMAGE_VERSION}", "-f ${buildContext}/Dockerfilechalk.deploy ${buildContext}")

                }
            }
        }
        stage('Publish') {
            steps {
                ansiColor('xterm') {
                sh "docker run --rm deploy > log.txt"
                }
		archiveArtifacts artifacts: 'log.txt', fingerprint: true
		writeFile file: 'version.txt', text: "IMAGE_VERSION=${env.IMAGE_VERSION}\n"
		archiveArtifacts artifacts: 'version.txt', fingerprint: true
            }
        }

    }
}

