FROM node:22

RUN apt update && apt install -y curl git
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \apt install -y nodejs

WORKDIR /app

RUN git clone https://github.com/devenes/node-js-dummy-test.git .

RUN npm install