FROM fedora:41

RUN dnf -y update && \
    dnf -y install meson gcc glib2-devel openssl-devel ncurses-devel utf8proc-devel perl-ExtUtil* cmake libgcrypt-config libgcrypt
RUN dnf -y install git
RUN git clone https://github.com/irssi/irssi
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build