FROM oceanbattle-build AS build

WORKDIR /app

RUN dotnet publish OceanBattle.WebAPI/OceanBattle.WebAPI.csproj \ 
  -c Release \
  -p:PublishSingleFile=true \
  -p:UseAppHost=true \
  -p:IncludeNativeLibrariesForSelfExtract=true \
  -p:PublishTrimmed=false \
  -p:DebugType=None \
  -p:DebugSymbols=false \
  --self-contained true \
  -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .
ENTRYPOINT ["./OceanBattle.WebAPI"]

EXPOSE 80