FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app
RUN apt update && apt install -y git

RUN git clone --recurse-submodules -j8 https://github.com/OceanBattle/OceanBattle.WebAPI.git .
RUN dotnet restore
RUN dotnet build
