FROM ubuntu:latest AS irssi_build

RUN apt update && apt install -y \
    build-essential meson ninja-build git perl pkg-config \
    libglib2.0-dev libssl-dev libncurses-dev

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /irssi

RUN meson Build 
RUN ninja -C Build && ninja -C Build install
