pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "tomaszek03/redis-app"
        IMAGE_TAG = 'v1.0.0'
    }
    
    stages {
        stage('Clone&Checkout') {
            steps {
                sh "rm -fr MDO2025_INO"
                sh "git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git"
                dir("MDO2025_INO") { sh "git checkout TM415261" }
            }
        }
        stage('Build') {
            steps {
                sh "docker build -t redis-builder -f MDO2025_INO/ITE/GCL05/TM415261/Sprawozdanie2/project/Dockerfile.build ."
            }
        }
        stage('Test') {
            steps {
                sh "docker build -t redis-test -f MDO2025_INO/ITE/GCL05/TM415261/Sprawozdanie2/project/Dockerfile.test ."
            }
        }
        stage('RunningTests') {
            steps {
                sh "docker run --rm redis-test"
            }
        }
        stage('Deploy') {
            steps {
                sh """
                    if [ \$(docker ps -a -q -f name=redis-deploy-test) ]; then
                        docker rm -f redis-deploy-test
                    fi
                """
                sh """ 
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f MDO2025_INO/ITE/GCL05/TM415261/Sprawozdanie2/Dockerfile.deploy .
                """
                echo "Testing deploy..."
                sh """
                    docker run -d --name redis-deploy-test -p 6379:6379 ${IMAGE_NAME}:${IMAGE_TAG}
                    sleep 5
                    docker exec redis-deploy-test redis-cli PING | grep PONG
                    docker exec redis-deploy-test redis-cli SET test_key "MyKey" | grep OK
                    docker exec redis-deploy-test redis-cli GET test_key | grep MyKey
                    docker stop redis-deploy-test
                    docker rm redis-deploy-test
                """
            }
        }
        stage('Publish') {
            steps {
                echo "Here will be a Publish stage"
            }
        }
    }
}
