FROM debian:bookworm-slim

RUN apt-get update -o Acquire::Check-Valid-Until=false \
 && apt-get install -y \
    build-essential \
    libssl-dev \
    libpcre3-dev \
    libapr1-dev libaprutil1-dev \
    python3 python3-venv python3-pip \
    autoconf automake libtool libtool-bin \
    make git wget curl unzip \
    libnghttp2-dev \
    nghttp2-client \
    libexpat1-dev \
    libldap2-dev \
 && python3 -m venv /opt/venv \
 && /opt/venv/bin/pip install --upgrade pip \
 && /opt/venv/bin/pip install \
      pytest \
      cryptography \
      pyOpenSSL \
      websockets \
      filelock \
 && rm -rf /var/lib/apt/lists/*

RUN curl -L -o /tmp/pebble.zip https://github.com/letsencrypt/pebble/releases/download/v2.0.9/pebble-v2.0.9-linux-amd64.zip && \
    unzip /tmp/pebble.zip -d /usr/local/bin && \
    rm /tmp/pebble.zip && \
    chmod +x /usr/local/bin/pebble

WORKDIR /httpd
COPY httpd/ /httpd/
