FROM debian:bookworm-slim

RUN apt-get update -o Acquire::Check-Valid-Until=false \
 && apt-get install -y \
    build-essential \
    libssl-dev \
    libpcre3-dev \
    libapr1-dev libaprutil1-dev \
    python3 python3-venv python3-pip \
    autoconf automake libtool libtool-bin \
    make git wget curl \
    libnghttp2-dev \
    nghttp2-client \
 && python3 -m venv /opt/venv \
 && /opt/venv/bin/pip install --upgrade pip \
 && /opt/venv/bin/pip install \
      pytest \
      cryptography \
      pyOpenSSL \
      websockets \
 && rm -rf /var/lib/apt/lists/*
