FROM fedora

RUN df -y install git meson gcc glib-devel openssl-devel ncurses-devel utf8proc-devel perl-ExtUtils*
RUN git clone https://github.com/irssi/irssi.git
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build
