FROM maven:3.9.9-eclipse-temurin-17 AS test

RUN apt-get update && apt-get install -y git curl

WORKDIR /app

RUN git clone https://github.com/sauer515/exam-seat-arrangement.git .

CMD ["mvn", "test"]