ARG BUILD_TAG

FROM skwasny/myapp:builder-${BUILD_TAG} AS builder

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY --from=builder /workspace/target/teacher-management-*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]