FROM eclipse-temurin:17-jdk AS build

RUN apt-get update && apt-get install -y git curl

WORKDIR /app

RUN git clone https://github.com/sauer515/exam-seat-arrangement.git .

RUN mvn clean package -DskipTests

RUN mkdir -p /app/target/dependency
WORKDIR /app/target/dependency
RUN jar -xf ../exam-seating-arrangement-*.jar