FROM maven:3.9.9-eclipse-temurin-17 AS build

RUN apt-get update && apt-get install -y git curl

WORKDIR /app

RUN git clone -b v2 --single-branch https://github.com/sauer515/exam-seat-arrangement.git .

RUN mvn clean package -DskipTests

RUN mkdir -p /app/target/dependency
WORKDIR /app/target/dependency
RUN jar -xf ../exam-seating-arrangement-*.jar