#!/bin/sh

EXPECTED_PREFIX="MK416388"

if [ ! -f "$1" ]; then
    echo "Błąd: Plik $1 nie istnieje!"
    exit 1
fi

COMMIT_MSG=$(cat "$1")

if [[ "$COMMIT_MSG" != $EXPECTED_PREFIX* ]]; then
    echo "Błąd: Commit message musi zaczynać się od $EXPECTED_PREFIX!"
    exit 1
fi

exit 0
