FROM node:latest

WORKDIR /app

RUN apk add --no-cache git
RUN git clone https://github.com/mareczek2115/cpm-app.git .

WORKDIR /app/frontend

RUN npm ci
RUN npm run build

CMD ["echo", "Build completed"]