#!/bin/bash
# Pobranie treści commit message
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Sprawdzenie, czy commit message zaczyna się od inicjałów i numeru indeksu
if [[ ! $COMMIT_MSG =~ ^JK414562 ]]; then
    echo "Błąd: Commit message musi zaczynać się od 'JK414562'."
    exit 1
fi
