FROM fedora:42

RUN dnf -y update &&\
    dnf -y install meson gcc glib2-devel openssl-devel ncurse-devel
RUN dnf -y install git
RUN git clone https://github.com/irssi/irssi
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build