FROM fedora:41

COPY mycjson.rpm /tmp/mycjson.rpm
RUN dnf install -y /tmp/mycjson.rpm gcc

COPY main.c /app/main.c
WORKDIR /app

RUN gcc main.c -o example -lcjson -I/usr/local/include/mycjson -L/usr/local/lib64
ENV LD_LIBRARY_PATH=/usr/local/lib64

CMD ["./example"]

