ARG IMAGE_TAG=latest
FROM redisbld:${IMAGE_TAG}

RUN dnf -y update && \
    dnf module enable tcl:8.6 -y && \
    dnf -y install \
    make \
    gcc \
    procps-ng \
    tcl \
    tcl-devel && \
    dnf clean all

WORKDIR /redis

RUN make test