FROM fedora:latest

RUN dnf -y update &&  dnf -y install openssh-server passwd &&  dnf clean all
RUN ssh-keygen -A
RUN echo "root:root" | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir -p /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]