pipeline {
    agent any

    stages {
        stage('Cleanup') {
            steps {
                sh 'docker rmi $(docker images -a -q)'
                sh 'rm -rf MDO2025_INO'
            }
        }
        
        stage('Checkout') {
            steps {
                git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO'
                dir('MDO2025_INO') {
                    sh 'git checkout KL417218'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('ITE/GCL05/KL417218/Sprawozdanie1') {
                    sh 'docker build -f Dockerfile.redisbuild -t redis-build .'    
                }
                
            }
        }
    }
}
