pipeline {
    agent any

    stages {
        stage('Cleanup') {
            steps {
                sh 'docker rmi $(docker images -a -q)'
                sh 'rm -rf MDO2025_INO'
            }
        }
        
        stage('Checkout') {
            steps {
                git 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO'
                dir('MDO2025_INO') {
                    sh 'git checkout KL417218'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir('ITE/GCL05/KL417218/Sprawozdanie1') {
                    sh 'docker build -f Dockerfile.redisbuild -t redis-build .'    
                }
                
            }
        }

        stage('Test') {
            steps {
                dir('ITE/GCL05/KL417218/Sprawozdanie1') {
                    sh 'docker build -f Dockerfile.redistest -t redis-test .'    
                }
            }
        }

        stage('Deploy') {
            steps {
               dir('ITE/GCL05/KL417218/Sprawozdanie2') {
                    sh 'docker build -f Dockerfile.redisdeploy -t redis-deploy .'
                    sh 'docker build -f Dockerfile.redisclient -t redis-client .'
                    sh 'docker network create redis-network'
                    sh 'docker run -d --name redis-server --network redis-network redis-deploy'
                    sh 'docker run -d --name redis-client --network redis-network redis-client redis-cli -h redis-server' 
                    sh 'docker exec redis-client ping'
                }
            }
        }

        stage('Publish') {
            steps {
              echo 'Publish will be here!'
            }
        }
    }
}
