pipeline {
    agent any

    environment {
        WORKDIR = "INO/GCL02/KK416269/redis_clone"
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git', branch: 'KK416269'
            }
        }

        stage('Build') {
            steps {
                dir("${WORKDIR}") {
                    script {
                        docker.build('redis_build_container', '-f Dockerfile.build --no-cache .')
                        def containerId = sh(script: "docker create redis_build_container", returnStdout: true).trim()
			sh 'mkdir -p artifacts'
                        sh "docker cp ${containerId}:/redis/src/redis-server artifacts/redis-server"
                        sh "docker cp ${containerId}:/redis/src/redis-cli artifacts/redis-cli"
                        sh "docker rm ${containerId}"
                    }
                }
            }
        }
        
        stage('Test') {
            steps {
                dir("${WORKDIR}") {
                    script {
                        docker.build('redis-test', '-f Dockerfile.test .')
                        sh 'mkdir -p logs'
                        def cid = sh(script: "docker create redis-test", returnStdout: true).trim()
                        sh "docker cp ${cid}:/redis/tests/test-results.log logs/redis_test.log || echo 'No logs found'"
                        sh "docker rm ${cid}"
                    }
                }
            }
        }

        stage('Runtime') {
            steps {
                dir("${WORKDIR}") {
                    script {
                        docker.build('redis_runtime', '-f Dockerfile.runtime .')
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh '''
                        docker stop redis_deploy_container || true
                        docker rm redis_deploy_container || true
                        docker run -d -p 6379:6379 --name redis_deploy_container redis_runtime
                    '''
                }
            }
        }

        stage('Connection') {
            steps {
                script {
                    sh '''
                        sleep 5
                        docker exec redis_deploy_container /app/redis-cli ping || echo "Redis nie odpowiada"
                    '''
                }
            }
        }

        stage('Publish') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        def imageName = "kaoina666/redis_runtime:${BUILD_NUMBER}"
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker tag redis_runtime ''' + imageName + '''
                            docker push ''' + imageName + '''
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker stop redis_deploy_container || true'
                sh 'docker rm redis_deploy_container || true'
            }
            dir("${WORKDIR}") {
                archiveArtifacts artifacts: 'artifacts/*', fingerprint: true
            }
            archiveArtifacts artifacts: 'INO/GCL02/KK416269/redis_clone/logs/**'
        }
    }
}
