FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=python-build /app /app

CMD ["make", "test"]


