FROM fedora:latest

RUN dnf -y update && dnf install -y git

WORKDIR /app

RUN git clone https://ghp_LKr12Pi0ORDv601bff1xuxnLm1ST5F3Nyj3@github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git

CMD ["bash"]
