FROM weatherapp-build AS build

WORKDIR /src/weatherapp-backend

RUN dotnet publish WeatherForecast.Api/WeatherForecast.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 5099

ENTRYPOINT ["dotnet", "WeatherForecast.Api.dll"]