# Dockerfile.deploy
FROM node:10

WORKDIR /app

# Skopiuj aplikację z kontekstu (np. z builda)
COPY . .

# Instalacja starszej wersji http-server kompatybilnej z Node 10
RUN npm install -g http-server@0.12.3

EXPOSE 8000

CMD ["http-server", "reports/coverage/lcov-report", "-p", "8000"]
