pipeline {
    agent any

    stages {
        stage('Clean repo') {
            steps {
                cleanWs()
            }
        }
        
        stage('Clone repo') {
            steps {
                git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git', branch: 'main'
            }
        }
        
        stage('Git checkout MZ412474') {
            steps {
                sh 'git checkout MZ412474'
            }
        }
        
        stage('Delete docker images') {
            steps {
                sh 'docker rmi -f weechat_build weechat_test'
            }
        }
        
        stage('Clean cache') {
            steps {
                sh 'docker builder prune -af'
            }
        }
        
        stage('Build Dockerfile.build') {
            steps {
                dir('ITE/GCL08/MZ412474/Sprawozdanie2') {
                    sh 'docker build -t weechat_build -f Dockerfile.build .'
                }
            }
        }
        
        stage('Build Dockerfile.test') {
            steps {
                dir('ITE/GCL08/MZ412474/Sprawozdanie2') {
                    sh 'docker build -t weechat_test -f Dockerfile.test .'
                }
            }
        }

        stage('Build rpm package') {
            steps {
                sh '''
                docker run --rm -v $(pwd)/output:/output weechat_build bash -c "
                set -e
                mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
                cd /app
                tar --exclude='weechat/build' \
                    --exclude='weechat/.git' \
                    -czf ~/rpmbuild/SOURCES/weechat-1.0.tar.gz \
                    --transform 's,^weechat,weechat-1.0,' \
                    weechat

                echo 'Name:           weechat' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'Version:        1.0' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'Release:        1%{?dist}' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'Summary:        WeeChat built from source' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'License:        GPLv3+' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'URL:            https://weechat.org/' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'Source0:        weechat-1.0.tar.gz' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'BuildRequires:  ncurses-devel' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'Requires:       ncurses' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '%description' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'WeeChat build for devops laboratory calsses' >> ~/rpmbuild/SPECS/weechat.spec &&
                
                echo '%prep' >> ~/rpmbuild/SPECS/weechat.spec &&
                
                echo '%setup -q' >> ~/rpmbuild/SPECS/weechat.spec &&

                echo '%build' >>  ~/rpmbuild/SPECS/weechat.spec &&
                echo 'rm -rf build' >>  ~/rpmbuild/SPECS/weechat.spec &&
                echo 'mkdir build' >>  ~/rpmbuild/SPECS/weechat.spec &&
                echo 'cd build' >>  ~/rpmbuild/SPECS/weechat.spec &&
                echo 'cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_PHP=OFF -DENABLE_LUA=OFF -DENABLE_TESTS=ON' >>  ~/rpmbuild/SPECS/weechat.spec &&
                echo 'make' >>  ~/rpmbuild/SPECS/weechat.spec &&

                echo '%install' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'cd build' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo 'make install DESTDIR=%{buildroot}' >> ~/rpmbuild/SPECS/weechat.spec &&
                
                echo '%files' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/bin/weechat*' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/include/weechat/' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/lib/pkgconfig/weechat.pc' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/lib/weechat/' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/share/applications/weechat.desktop' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/share/icons/hicolor/*/apps/weechat.png' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '/usr/share/locale/*/LC_MESSAGES/weechat.mo' >> ~/rpmbuild/SPECS/weechat.spec &&
                
                echo '%changelog' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '* Sat May 03 2025 - 1.0-1' >> ~/rpmbuild/SPECS/weechat.spec &&
                echo '- Initial RPM build' >> ~/rpmbuild/SPECS/weechat.spec

                rpmbuild -ba ~/rpmbuild/SPECS/weechat.spec

                cp -v ~/rpmbuild/RPMS/x86_64/*.rpm /output/
                "
                '''
        }
    }

        stage('Archive artifacts') {
            steps {
                archiveArtifacts artifacts: 'output/*.rpm', fingerprint: true
            }
        }

    }
}