pipeline {
    agent any

    stages {
        stage('Clone') { 
            steps {
                git branch: 'PS417478', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
            }
        }

        stage('Clear Docker cache') {
            steps {
                sh 'docker builder prune -af'
            }
        }

        stage('Build') {
            steps {
                dir("INO/GCL02/PS417478/Sprawozdanie2/pipeline") {
                    script {
                        docker.build('cjson-build', '-f Dockerfile.build .')

                        sh '''
                            mkdir -p ../artifacts
                            CID=$(docker create cjson-build)
                            docker cp $CID:/app/cjson.rpm ../artifacts/
                            docker rm $CID
                        '''
                    }
                }
            }
        }

        stage('Test') {
            steps {
                dir("INO/GCL02/PS417478/Sprawozdanie2/pipeline") {
                    script {
                        docker.build('cjson-test', '-f Dockerfile.test .')

                        sh """
                            docker run --rm cjson-test | tee ../artifacts/cjson_test.log
                        """
                    }
                }    
            }
        }

        stage('Deploy') {
            steps {
                dir("INO/GCL02/PS417478/Sprawozdanie2/pipeline") {
                    script {
                        sh 'cp ../artifacts/cjson.rpm .'
                        docker.build("cjson-deploy", "-f Dockerfile.deploy .")

                        sh """
                            docker run --rm cjson-deploy | tee ../artifacts/cjson_deploy.log
                        """
                    }      
                }
            }
        }

        stage('Publish') {
            steps {
                archiveArtifacts artifacts: 'INO/GCL02/PS417478/Sprawozdanie2/artifacts/*.log', fingerprint: true
                archiveArtifacts artifacts: 'INO/GCL02/PS417478/Sprawozdanie2/artifacts/*.rpm', fingerprint: true
            }
        }
    }
}