pipeline {
    agent any
    environment {
        MAVEN_OPTS = '-Dmaven.repo.local=.m2/repository'
        BUILD_IMAGE = 'mvn-build'
        TEST_IMAGE = 'mvn-test'
        RUNTIME_IMAGE = 'openjdk:17-slim'
        JAR_NAME = 'artifact.jar'
        ARTIFACT_DIR = 'publish'
        DOCKERFILES_DIR = 'INO/GCL01/KK415853/Sprawozdanie2'
    }
    stages {
        stage('Clone repo') {
            steps {
                git branch: 'KK415853', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
            }
        }
        stage('Build Builder Image') {
            steps {
                sh "docker build -t ${BUILD_IMAGE} -f ${DOCKERFILES_DIR}/Dockerfile.build ${DOCKERFILES_DIR}"
            }
        }
        stage('Build Test Image') {
            steps {
                sh "docker build -t ${TEST_IMAGE} -f ${DOCKERFILES_DIR}/Dockerfile.test ${DOCKERFILES_DIR}"
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                    TEST_CONTAINER_ID=$(docker create ${TEST_IMAGE})
                    docker start -a $TEST_CONTAINER_ID
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    docker rm -f running-java-app || true
                    docker run -d \
                        --name running-java-app \
                        -v "$PWD/${JAR_NAME}:/app/${JAR_NAME}" \
                        ${RUNTIME_IMAGE} \
                        java -jar /app/${JAR_NAME}
                '''
            }
        }
        stage('Publish') {
            steps {
                sh '''
                    mkdir -p ${ARTIFACT_DIR}
                    cp ${JAR_NAME} ${ARTIFACT_DIR}/myapp-1.0.0.jar
                '''
                archiveArtifacts artifacts: "${ARTIFACT_DIR}/*.jar"
            }
        }
    }
    post {
        always {
            sh 'docker rm -f running-java-app || true'
        }
    }
}