# ─── Builder: Fedora + zależności + klon IRSSI ─────────────────────────────────
FROM fedora:latest

RUN dnf -y install \
        gcc glib2-devel openssl-devel ncurses-devel \
        meson ninja git perl-ExtUtils-Embed \
    && dnf clean all

WORKDIR /app

# pobieramy najnowsze źródła IRSSI (1 commit depth, szybciej)
RUN git clone --depth 1 https://github.com/irssi/irssi.git .

# konfiguracja + kompilacja
RUN meson setup builddir && \
    ninja -C builddir
