FROM ubuntu:latest

RUN apt update
RUN apt install -y build-essential git curl

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN git clone https://github.com/SkaneroOo/kagikachi
WORKDIR /kagikachi

RUN cargo build --release