#!/bin/bash

PREFIX="FN414313"

COMMIT_MSG_FILE="$1"

FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

if [[ ! "$FIRST_LINE" =~ ^"$PREFIX" ]]; then
    echo  "Błąd: Commit message musi zaczynać się od: '$PREFIX'"
    exit 1  
fi

exit 0  

