pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
        BRANCH_NAME = 'KK416776'  
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${BRANCH_NAME}", url: "${GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t my_image ."
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    sh "docker run -d --name my_container my_image"
                }
            }
        }
    }

    post {
        always {
            script {
                sh "docker rm -f my_container || true"
                sh "docker rmi my_image || true"
            }
        }
    }
}
