FROM ubuntu:latest

LABEL maintainer="Kefireczek <kefireczek.pl@gmail.com>"

RUN apt update && apt upgrade -y

WORKDIR /app

RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git
