# Dockerfile.runtime
FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    libglib2.0-0 libssl1.1 libncurses5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=bambusscooby/irssi-builder:${BUILD_NUMBER} /src/builddir/irssi /usr/local/bin/irssi

ENTRYPOINT ["irssi"]
