# Dockerfile.runtime
FROM debian:bullseye AS runtime

RUN apt-get update && apt-get install -y \
    libglib2.0-0 libssl1.1 libncurses5 \
    && rm -rf /var/lib/apt/lists/*

ARG BUILDER_TAG
COPY --from=bambusscooby/irssi-builder:${BUILDER_TAG} /src/builddir/irssi /usr/local/bin/irssi

ENTRYPOINT ["irssi"]
