FROM fedora:42
RUN dnf install -y \
    meson \
    ninja \
    gcc \
    glib2-devel \
    openssl-devel \
    utf8proc-devel \
    ncurses-devel \
    perl
RUN --mount=type=cache,target=/git_cache git clone https://github.com/irssi/irssi
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build 
RUN mkdir -p /output && cp -r Build /output
CMD ["/bin/bash"]