FROM fedora:41

RUN dnf -y update && \
    dnf clean all

RUN useradd -m appuser

COPY --from=sqlite-build /sqlite/sqlite3 /sqlite/sqlite3

COPY smoke-test.sh /smoke-test.sh
RUN chmode -x /sqlite/sqldiff /sqlite/sqldiff /sqlite/sqlite3_analyzer /sqlite/sqlite3_rsync /smoke-test.sh

USER appuser

CMD ["./smoke-test.sh"]