FROM fedora:41

RUN dnf install -y git gcc make tcl-devel

RUN git clone https://github.com/sqlite/sqlite.git
WORKDIR /sqlite

RUN ./configure

RUN make
RUN make sqldiff 
RUN make sqlite3_analyzer
RUN make sqlite3_rsync 
