# Dockerfile.build
FROM ubuntu:24.04

RUN apt update && apt install -y \
    git \
    gcc \
    make \
    meson \
    ninja-build \
    pkg-config \
    libglib2.0-dev \
    libssl-dev \
    libncurses-dev \
    perl \
    cmake \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /app/irssi

RUN meson setup build && meson compile -C build

RUN mkdir /output && cp -r /app/irssi/build/* /output/


