FROM node:23-alpine as nodebld

RUN apk add --no-cache git

RUN git clone https://github.com/devenes/node-js-dummy-test
WORKDIR /node-js-dummy-test
RUN npm install


FROM node:23-alpine

COPY --from=nodebld /node-js-dummy-test /node-js-dummy-test
WORKDIR /node-js-dummy-test


RUN npm install


EXPOSE 3000

CMD ["/bin/false"]