FROM fedora:latest

RUN dnf update -y && dnf install -y cmake \
g++ \
git

WORKDIR /app
RUN git clone https://github.com/doctest/doctest.git ./doctest
RUN cd doctest && mkdir build && cd build && cmake .. && make -j$(nproc)

CMD ["/bin/bash"]ers