FROM ubuntu:latest
RUN apt update && apt install -y build-essential cmake make gcc git
WORKDIR /app
RUN git clone https://github.com/DaveGamble/cJSON.git && cd cJSON && mkdir build && cd build
WORKDIR /app/cJSON/build
RUN cmake .. && make
