FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    git \
    meson \
    build-essential \
    ninja-build \
    pkg-config \
    libglib2.0-dev \
    libncurses5-dev \
    libssl-dev
RUN git clone https://github.com/irssi/irssi /irssi
WORKDIR /irssi
RUN meson setup build
WORKDIR /irssi/build
RUN ninja
CMD ["bash"]
