FROM node AS express-build

RUN git clone https://github.com/expressjs/express

RUN npm install -g express-generator@4

RUN express /tmp/foo

WORKDIR /tmp/foo

RUN sed -i '/block content/a\  p Version 2!' views/index.jade \
 && cat views/index.jade

RUN npm install