FROM node:16

ARG VERSION_NUMBER=dev

RUN git clone https://twoje-repo.git /app

WORKDIR /app

RUN echo "app.get('/version', (req, res) => res.send('Version v${VERSION_NUMBER}'));" >> app.js

RUN npm install

EXPOSE 3000

CMD ["node", "app.js"]
