FROM node AS express-build

RUN git clone https://github.com/expressjs/express

RUN npm install -g express-generator@4

RUN express /tmp/foo

WORKDIR /tmp/foo

RUN npm install

RUN echo "app.get('/version', (req, res) => res.send('New Version!'));" >> /tmp/foo/app.js