# Dockerfile (build)
FROM ubuntu:latest

# Zainstaluj wymagane zależności
RUN apt-get update && \
    apt-get install -y build-essential autoconf automake libtool pkg-config libglib2.0-dev libssl-dev libncurses5-dev perl zlib1g-dev meson ninja-build git

# Sklonuj repozytorium Irssi
RUN git clone https://github.com/irssi/irssi /irssi

# Utwórz katalog build i skonfiguruj build
WORKDIR /irssi/build
RUN meson ..

# Skompiluj Irssi
RUN ninja
