FROM fedora:42
RUN dnf install -y git \
    meson \
    ninja \
    gcc \
    glib2-devel \
    openssl-devel \
    utf8proc-devel \
    ncurses-devel \
    perl
RUN git clone https://github.com/irssi/irssi
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build