pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
        BRANCH = 'AR417143'
        DOCKERFILE_BUILD_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.build'
        DOCKERFILE_TEST_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.test'
        DOCKERFILE_DEPLOY_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.deploy'
        DOCKERFILE_RUNTIME_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.runtime'
        DOCKER_CONTEXT = 'ITE/GCL06/AR417143/006-Class'
        DOCKER_IMAGE = 'wget-jenkins-build-fedora'
        DEPLOY_IMAGE = 'wget-deploy-test-fedora'
        TEST_IMAGE = 'wget-tester-fedora'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Check') {
            steps {
                sh "ls -la ${DOCKER_CONTEXT}"
                sh "cat ${DOCKERFILE_BUILD_PATH}"
            }
        }

        stage('Build Docker image') {
            steps {
                sh "docker build --no-cache -t ${DOCKER_IMAGE} -f ${DOCKERFILE_BUILD_PATH} ${DOCKER_CONTEXT}"
            }
        }

        stage('Deploy and Test wget') {
            steps {
                echo 'Build deploy-image'
                sh "docker build --no-cache -t ${DEPLOY_IMAGE} -f ${DOCKERFILE_DEPLOY_PATH} ${DOCKER_CONTEXT}"
                echo 'Run container'
                sh "docker run --rm ${DEPLOY_IMAGE}"
            }
        }
        
        stage('Build wget .rpm package') {
           steps {
                echo 'Build wget.rpm'
                sh 'docker create --name wget-builder ${DOCKER_IMAGE}'
                sh 'docker cp wget-builder:/opt/wget/wget-1.0-1.fc38.x86_64.rpm wget.rpm'
                sh 'docker rm wget-builder'
                archiveArtifacts artifacts: 'wget.rpm', fingerprint: true
            }
        }
        
        stage('Test wget') {
           steps {
                echo 'Build test image'
                sh "docker build --no-cache -t ${TEST_IMAGE} -f ${DOCKERFILE_TEST_PATH} ${DOCKER_CONTEXT}"
                echo 'Run wget tests'
                sh "docker run --rm ${TEST_IMAGE}"
            }
        }
        
        stage('Publish Runtime Image') {
           steps {
                echo 'Copy wget.rpm'
                sh 'cp wget.rpm ${DOCKER_CONTEXT}'
                echo 'Build runtime image'
                sh 'docker build --no-cache -t wget-runtime-fedora -f ${DOCKERFILE_RUNTIME_PATH} ${DOCKER_CONTEXT}'
                echo 'Run wget runtime container'
                sh 'docker run --rm wget-runtime-fedora'
            }
        }
    }

    post {
        success {
            echo 'Succes.'
        }
        failure {
            echo 'Pipeline error.'
        }
    }
}