pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
        BRANCH = 'AR417143'
        DOCKERFILE_BUILD_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.build'
        DOCKERFILE_TEST_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.test'
        DOCKERFILE_DEPLOY_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.deploy'
        DOCKERFILE_RUNTIME_PATH = 'ITE/GCL06/AR417143/006-Class/Dockerfile.runtime'
        DOCKER_CONTEXT = 'ITE/GCL06/AR417143/006-Class'
        DOCKER_IMAGE = 'wget-jenkins-build-fedora'
        DEPLOY_IMAGE = 'wget-deploy-test-fedora'
        TEST_IMAGE = 'wget-tester-fedora'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Check') {
            steps {
                sh "ls -la ${DOCKER_CONTEXT}"
                sh "cat ${DOCKERFILE_PATH}"
            }
        }

        stage('Build Docker image') {
            steps {
                sh "docker build --no-cache -t ${DOCKER_IMAGE} -f ${DOCKERFILE_PATH} ${DOCKER_CONTEXT}"
            }
        }

        stage('Deploy and Test wget') {
            steps {
                echo 'Buduję deploy-image do testu wget'
                sh "docker build --no-cache -t ${DEPLOY_IMAGE} -f ITE/GCL06/JR414539/Sprawozdanie2/Dockerfile_deploy ITE/GCL06/JR414539/Sprawozdanie2"
                echo 'Odpalam kontener i testuję wget'
                sh "docker run --rm ${DEPLOY_IMAGE}"
            }
        }
        
        stage('Build wget .rpm package') {
           steps {
                echo 'Buduję paczkę wget.rpm'
                sh 'docker create --name wget-builder ${DOCKER_IMAGE}'
                sh 'docker cp wget-builder:/opt/wget/wget-1.0-1.fc38.x86_64.rpm wget.rpm'
                sh 'docker rm wget-builder'
                archiveArtifacts artifacts: 'wget.rpm', fingerprint: true
            }
        }
        
        stage('Test wget') {
           steps {
                echo 'Buduję obraz tester-a'
                sh "docker build --no-cache -t ${TEST_IMAGE} -f ITE/GCL06/JR414539/Sprawozdanie2/Dockerfile.test ITE/GCL06/JR414539/Sprawozdanie2"
                echo 'Odpalam testy wget'
                sh "docker run --rm ${TEST_IMAGE}"
            }
        }
        
        stage('Publish Runtime Image') {
           steps {
                echo 'Kopiuję wget.rpm do katalogu Sprawozdanie2'
                sh 'cp wget.rpm ITE/GCL06/JR414539/Sprawozdanie2/'
                echo 'Buduję runtime image z wget'
                sh 'docker build --no-cache -t wget-runtime-fedora -f ITE/GCL06/JR414539/Sprawozdanie2/Dockerfile.runtime ITE/GCL06/JR414539/Sprawozdanie2'
                echo 'Odpalam kontener runtime z wget'
                sh 'docker run --rm wget-runtime-fedora'
            }
        }
    }

    post {
        success {
            echo 'Succes.'
        }
        failure {
            echo 'Pipeline error.'
        }
    }
}