FROM ubuntu:22.04

RUN apt update && apt install -y \
    build-essential \
    autoconf \
    automake \
    autopoint \
    texinfo \
    flex \
    gperf \
    gettext \
    libssl-dev \
    libgnutls28-dev \
    zlib1g-dev \
    pkg-config \
    git \
    wget \
    autoconf-archive \
    ca-certificates

WORKDIR /opt

RUN git clone https://git.savannah.gnu.org/git/wget.git

WORKDIR /opt/wget

RUN ./bootstrap && ./configure && make

CMD ["/bin/bash"]
