FROM fedora:41
RUN dnf -y update && \
    dnf -y install gcc make openssl-devel libcurl-devel zlib-devel \
    autoconf automake libtool git wget && \
    dnf clean all
RUN git clone https://github.com/curl/curl.git
WORKDIR /curl
RUN ./buildconf && ./configure --with-openssl && make && make install
CMD ["/bin/bash"]