FROM redis-builder AS builder
FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y libjemalloc2 && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/redis/src/redis-server /usr/local/bin/
COPY --from=builder /app/redis/src/redis-cli /usr/local/bin/
ENTRYPOINT ["redis-server"]
CMD ["--protected-mode", "no"]
