pipeline {
    agent any
    stages {
        stage('Cleaning') {
            steps {
                sh "rm -fr MDO2025_INO"
                sh "git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git"
                dir("MDO2025_INO") {
                    sh "git checkout MK415056"
                }
            }
        }
        stage('Builder') {
            steps {
                dir("MDO2025_INO") {
                    sh "docker build -t redis-builder -f ITE/GCL04/MK415056/sprawozdanie2/red/Dockerfile ."
                }
            }
        }
        stage('Tester') {
            steps {
                dir("MDO2025_INO") {
                    sh "docker build -t redis-test -f ITE/GCL04//MK415056/sprawozdanie2/red/Dockerfile_test ."
                    sh "docker run redis-test "
                }
            }
        }
	    stage('Deploy') {
            steps {
                   dir("MDO2025_INO") {
    		        sh """ 
                        docker build --no-cache -t marekkubi/pipeline-redis:v1.0.${BUILD_NUMBER} -f ITE/GCL04/MK415056/sprawozdanie2/zaj5/Dockerfile_dep . 
                        docker network inspect network-testing >/dev/null 2>&1 || docker network create network-testing
    		            if [ \$(docker ps -a -q -f name=redis-testing-deploy) ]; then
                            docker rm -f redis-testing-deploy
                        fi
                        docker run -d --name redis-testing-deploy --network network-testing marekkubi/pipeline-redis:v1.0.${BUILD_NUMBER}
                        sleep 10
                        docker run --rm --network network-testing redis redis-cli -h redis-testing-deploy PING | grep PONG
                        docker run --rm --network network-testing redis redis-cli -h redis-testing-deploy SET test_key "MyKey" | grep OK
                        docker run --rm --network network-testing redis redis-cli -h redis-testing-deploy GET test_key | grep MyKey
                        docker stop redis-testing-deploy
                        docker rm redis-testing-deploy
                        docker network rm network-testing
                    """
                }
            }
        }
        stage('Publish') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'pass-dockhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push marekkubi/pipeline-redis:v1.0.${BUILD_NUMBER}
                        docker tag marekkubi/pipeline-redis:v1.0.${BUILD_NUMBER} marekkubi/pipeline-redis:latest
                        docker push marekkubi/pipeline-redis:latest
                    '''
                }
            }
        }
    }
}
