pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                sh 'docker rmi build test artifact || true'
            }
        }

        stage('Build') {
            steps {
                dir('ITE/GCL07/AS416588/Sprawozdanie1') {
                    sh 'docker build --no-cache -t build -f Dockerfile.lab3.1 .'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ITE/GCL07/AS416588/Sprawozdanie1') {
                    sh 'docker build --no-cache --progress=plain -t test -f Dockerfile.lab3.2 . 2>&1 | tee test-output.log'
                    sh "mv test-output.log test-logs-${BUILD_NUMBER}.log"
                }
            }
            post {
                always {
                    dir('ITE/GCL07/AS416588/Sprawozdanie1') {
                        archiveArtifacts artifacts: "test-logs-${BUILD_NUMBER}.log", fingerprint: true
                    }
                }
            }
        }

        stage('Build Artifact') {
            steps {
                dir('ITE/GCL07/AS416588/Sprawozdanie2') {
                    sh 'docker build --no-cache -t artifact -f Dockerfile.flatpak .'
                    sh 'docker run --rm --privileged -v .:/out artifact'
                    sh "mv irssi.flatpak irsii-${BUILD_NUMBER}.flatpak"
                }
            }
            post {
                always {
                    dir('ITE/GCL07/AS416588/Sprawozdanie2') {
                        archiveArtifacts artifacts: "irsii-${BUILD_NUMBER}.flatpak", fingerprint: true
                    }
                }
            }
        }

        stage('Smoke Test') {
            steps {
                dir('ITE/GCL07/AS416588/Sprawozdanie2') {
                    sh '''
                        docker run -it --rm \
                            -v .:/flatpak \
                            --cap-add=SYS_ADMIN \
                            --device=/dev/fuse \
                            --security-opt seccomp=unconfined \
                            freedesktop-sdk/flatpak bash -c '
                                flatpak install --user /app/irssi-*.flatpak -y
                                flatpak run com.example.irssi --version
                            '
                    '''
                }
            }
        }

    }
}