ARG BUILDER_IMAGE=builder:latest
FROM ${BUILDER_IMAGE} AS builder
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm","start"]