#syntax=docker/dockerfile:1.3
ARG BUILDER_IMAGE
FROM ${BUILDER_IMAGE} AS node_app_build
FROM node:18-alpine
WORKDIR /app
COPY --from=node_app_build /AGH-Node-Calculator-DevOps/node_modules ./node_modules
COPY --from=node_app_build /AGH-Node-Calculator-DevOps ./
EXPOSE 3000
CMD ["npm", "start"]
