FROM fedora

RUN dnf --assumeyes install git meson gcc glib2-devel ninja openssl-devel utf8proc-devel ncurses-devel perl-ExtUtils-Embed 

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /irssi

RUN meson Build && ninja -C Build && ninja -C Build install
