FROM ubuntu:latest

RUN apt update && apt install -y rpm gcc && ldconfig

COPY cjson.rpm /tmp/cjson.rpm
RUN rpm -i /tmp/cjson.rpm && ldconfig

# test
RUN find / -name "libcjson.so*" || true

COPY main.c /app/main.c
WORKDIR /app

RUN gcc main.c -o example -lcjson -I/usr/local/include/cjson -L/usr/local/lib64

ENV LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

CMD ["./example"]
