FROM ubuntu:latest

COPY cjson.rpm /tmp/cjson.rpm
RUN apt update && apt install -y /tmp/cjson.rpm gcc && ldconfig

ENV LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

COPY main.c /app/main.c
WORKDIR /app

RUN gcc main.c -o example -lcjson -I/usr/local/include/cjson -L/usr/local/lib64
CMD ["./example"]
