FROM node:latest

RUN apt-get update && apt-get install -y git

WORKDIR /app

RUN git clone https://github.com/mareczek2115/cpm-app.git .

WORKDIR /app/frontend

RUN npm install

CMD ["npm", "run", "dev"]
