#!/bin/bash

EXPECTED_PREFIX="WSZ417391"
COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(head -n1 "$COMMIT_MSG_FILE")

if [[ ! $COMMIT_MSG =~ ^$EXPECTED_PREFIX ]]; then
  echo "❌ Error: Commit message must start with \"$EXPECTED_PREFIX\"."
  exit 1
fi
