pipeline {
    agent any

    environment {
        //Dockerfiles
        DOCKERFILES_PATH = 'ITE/GCL04/JL416317/Sprawozdanie2/dockerfiles'
        DOCKERFILE_BUILD = 'Dockerfile.build'
        DOCKERFILE_TEST = 'Dockerfile.test'
        DOCKERFILE_DEPLOY = 'Dockerfile.deploy'
        
        //Images
        IMAGE_BUILD = 'weatherapp-build'
        IMAGE_TEST = 'weatherapp-test'
        IMAGE_DEPLOY = 'weatherapp-deploy'
        
        //Containers
        CONTAINER_DEPLOY = 'weatherapp'
        
        //Health check
        API_HEALTHCHECK_URL = 'http://localhost:8080/api/apihealth'
        
        //Publish
        ARTIFACTS_PATH = 'artifacts'

        //Flags
        DEBUG_FLAG = 'true'
    }

    stages {
        stage('Workspace cleanup') {
            steps {
                echo 'Cleaning containers...'
                sh """
                    docker container prune -f
                    docker rm -f ${CONTAINER_DEPLOY} || true
                """
                echo 'Cleaning images...'
                sh """
                    docker image prune -f
                    docker rmi -f ${IMAGE_BUILD} ${IMAGE_TEST} ${IMAGE_DEPLOY} || true
                """
            }
        }

        stage('Build') {
            steps {
                dir("${DOCKERFILES_PATH}") {
                    sh "docker build --no-cache -t ${IMAGE_BUILD} -f ${DOCKERFILE_BUILD} ."
                }
            }
        }
        
        stage('[Debug]: Build') {
            when {
                expression { env.DEBUG_INFO == 'true' }
            }
            steps {
                sh 'docker images'
            }
        }

        stage('Test') {
            steps {
                 dir("${DOCKERFILES_PATH}") {
                    sh "docker build --no-cache -t ${IMAGE_TEST} -f ${DOCKERFILE_TEST} ."
                }
            }
        }

        stage('[Debug]: Test') {
            when {
                expression { env.DEBUG_INFO == 'true' }
            }
            steps {
                sh 'docker images'
            }
        }
        
        stage('Deploy') {
            steps {
                dir("${DOCKERFILES_PATH}") {
                    sh """
                        docker build --no-cache -t ${IMAGE_DEPLOY} -f ${DOCKERFILE_DEPLOY} .
                        docker run -d --name ${CONTAINER_DEPLOY} ${IMAGE_DEPLOY}
                    """
                }
            }
        }

        stage('[Debug]: Deploy') {
            when {
                expression { env.DEBUG_INFO == 'true' }
            }
            steps {
                sh '''
                    docker images
                    docker ps -a
                '''
            }
        }
        

        stage('App startup') {
            steps {
                sh '''
                    for i in {1..30}; do
                        STATUS=$(docker exec ${CONTAINER_DEPLOY} curl -s -o /dev/null -w "%{http_code}" ${API_HEALTHCHECK_URL})
                        if [ "$STATUS" -eq 200 ]; then
                            exit 0
                        fi
                        sleep 5
                    done
                    echo "Application is not running!"
                    exit 1
                '''
            }
            
        }

        stage('[Debug]: App startup') {
            when {
                expression { env.DEBUG_INFO == 'true' }
            }
            steps {
                sh "docker logs ${CONTAINER_DEPLOY}"
            }
        }
        
        stage('Health check') {
            steps {
                sh '''
                    set -e
                    STATUS=$(docker exec ${CONTAINER_DEPLOY} curl -s -o /tmp/response.txt -w "%{http_code}" ${API_HEALTHCHECK_URL})
                    docker exec ${CONTAINER_DEPLOY} cat /tmp/response.txt
                    [ "$STATUS" -eq 200 ]
                '''
            }
        }
        
        stage('Publish') {
            steps {
                sh """
                    mkdir -p ${ARTIFACTS_PATH}
                    docker cp ${CONTAINER_DEPLOY}:/app ${ARTIFACTS_PATH}
                """
                archiveArtifacts artifacts: "${ARTIFACTS_PATH}/**", fingerprint: true
            }
        }
    }

    post {
        always {
            echo 'Cleaning containers...'
            sh """
                docker container prune -f
                docker rm -f ${CONTAINER_DEPLOY} || true
            """
            echo 'Cleaning images...'
            sh """
                docker image prune -f
                docker rmi -f ${IMAGE_BUILD} ${IMAGE_TEST} ${IMAGE_DEPLOY} || true
            """
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}