FROM nginx-build

WORKDIR /

RUN apt install -y perl cpanm

RUN cpanm FCGI Win32API::File GD Protocol::WebSocket SCGI Cache::Memcached

RUN git clone https://github.com/nginx/nginx-tests

WORKDIR /nginx-tests

RUN prove -v .