FROM ubuntu:latest

RUN apt update && apt install -y git gcc make libpcre3-dev zlib1g-dev libcurl4-openssl-dev

RUN git https://github.com/nginx/nginx.git 

WORKDIR /nginx

RUN ./auto/configure && make