FROM fedora:latest

RUN dnf -y update
RUN dnf -y install git ninja-build meson gcc glib2-devel openssl-devel ncurses-devel perl

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /irssi

RUN meson setup Build

RUN ninja -C Build