FROM ubuntu:latest

RUN apt-get update && apt install -y gcc g++ clang cmake pkgconf libncurses-dev libcurl4-gnutls-dev libgcrypt20-dev libgnutls28-dev zlib1g-dev gettext ca-certificates libcjson-dev libzstd-dev libaspell-dev python3-dev libperl-dev ruby-dev tcl-dev guile-3.0-dev libnode-dev libxml2-dev libargon2-dev libsodium-dev asciidoctor libcpputest-dev locales

RUN locale-gen en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

WORKDIR /app
