FROM weatherapp-build AS publish

WORKDIR /src/weatherapp-backend

RUN dotnet publish WeatherForecast.Api/WeatherForecast.Api.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 5099
ENTRYPOINT ["dotnet", "WeatherForecast.Api.dll"]
