FROM node:20

WORKDIR /app

# Wolumin wejściowy: kod źródłowy
VOLUME /app/source

# Wolumin wyjściowy: pliki builda
VOLUME /app/build

RUN apt remove -y git || true  # Usuwamy git na wszelki wypadek

CMD ["/bin/sh"]

