FROM ubuntu:22.04

RUN apt update && apt install -y \
    git build-essential meson ninja-build \
    autoconf automake pkg-config \
    libglib2.0-dev libssl-dev libperl-dev libncurses-dev \
    libutf8proc-dev libgcrypt20-dev libotr5-dev \
    libperl5.34 perl-modules-5.34 perl

WORKDIR /irssi

RUN git clone https://github.com/irssi/irssi.git . && \
    meson build && \
    ninja -C build
