FROM fedora:latest

RUN dnf install -y make gcc-c++ cmake git && \
    dnf clean all

WORKDIR /app
RUN git clone https://github.com/doctest/doctest.git && \
    cd doctest && mkdir build

WORKDIR /app/doctest/build
RUN cmake .. && make

CMD ["/bin/bash"]
