FROM node:16
RUN --mount=type=volume,source=input_volume,target=/mnt/input \
    --mount=type=volume,source=output_volume,target=/mnt/output \
    git clone https://github.com/devenes/node-js-dummy-test.git /mnt/input && \
    cd /mnt/input && \
    npm install && \
    npm run build
