pipeline {
    agent any

    environment {
        PROJECT_DIR = 'ITE/GCL06/DR416985/lab5'
        BUILD_IMAGE = 'node-build-image'
        TEST_IMAGE = 'node-test-image'
        DEPLOY_IMAGE = 'node-deploy-image'
    }

    stages {
        stage('Pobieranie kodu') {
            steps {
                git branch: 'DR416985', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git'
            }
        }

        stage('Build') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "docker build -t ${BUILD_IMAGE} -f node-build.Dockerfile ."
                }
            }
        }

        stage('Test') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "docker build -t ${TEST_IMAGE} -f node-test.Dockerfile ."
                    sh "docker run --rm ${TEST_IMAGE}"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker network create my_network || true'
                dir("${PROJECT_DIR}") {
                    sh """
                        docker build -t ${DEPLOY_IMAGE} -f node-Deploy.Dockerfile .
                        docker rm -f app || true
                        docker run -d -p 3000:3000 --name app --network my_network ${DEPLOY_IMAGE}
                    """
                }
            }
        }

        stage('Sprawdzenie działania aplikacji') {
            steps {
                sh 'docker run --rm --network my_network curlimages/curl:latest curl http://app:3000'
            }
        }
    }

    post {
        success {
            echo ' Pipeline zakończony sukcesem.'
        }
        failure {
            echo ' Pipeline zakończył się błędem.'
        }
    }
}
