FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y git meson build-essential ninja-build pkg-config \
    libglib2.0-dev libssl-dev perl libncurses-dev
ENV USER=root

WORKDIR /build

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /build/irssi

RUN meson Build

RUN ninja -C Build