#!/bin/bash

#Pobierz zawartość wiadomości commit
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

#Sprawdź, czy zawartość wiadomości rozpoczyna się od "TM415261"
if ! echo "$COMMIT_MSG" | grep -qE '^TM415261'; then
  echo "Błąd: Wiadomość commit musi rozpoczynać się od 'TM415261'."
  exit 1
fi

exit 0
