FROM node:latest

RUN apt update && apt install -y git

WORKDIR /app

RUN git clone https://github.com/ChristianKienle/nodejs-template.git

WORKDIR /app/nodejs-template

RUN npm ci
RUN npm run build

CMD ["echo", "Build completed!"]
