FROM chalk-build

WORKDIR /chalk-pipe

# Czyścimy wszystko, zostawiamy tylko bibliotekę i zależności
RUN rm -rf \
    .git \
    .github \
    .gitignore \
    .nprmc \
    LICENSE \
    README.md \
    tsconfig.json \
    screenshot.png \
    coverage \
    test \
    source \
    package-lock.json


COPY example.js .

CMD ["node", "example.js"]
