FROM node:slim

WORKDIR /app
COPY --from=nodebuild /app/node_modules /app/node_modules
COPY --from=nodebuild /app/package*.json /app/
COPY --from=nodebuild /app/src /app/src
COPY --from=nodebuild /app/public /app/public

EXPOSE 3000
CMD ["npm", "start"]