FROM node:18-slim

ARG NPM_TOKEN

WORKDIR /app

COPY --from=nodebuild /app/package*.json /app/

COPY . .

RUN npm install

RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

CMD ["npm", "publish", "--access", "public"]