pipeline {
    agent any

    environment {
        IMAGE_BUILD = 'node-build'
        IMAGE_TEST = 'node-test'
        IMAGE_DEPLOY = 'node-deploy'
        DOCKERHUB_REPO = 'winterwollf/node-deploy'
        ZIP_BASE = 'app'
        VERSION = "v${BUILD_NUMBER}"
        IMAGE_TAG = "winterwollf/node-deploy:v${BUILD_NUMBER}"
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'WSZ417391', url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO'
            }
        }

        stage('Clean') {
            steps {
                dir('ITE/GCL07/WSZ417391/Sprawozdanie2') {
                    sh '''
                        docker container ls -a -q | xargs -r docker rm -f
                        docker volume ls -q | xargs -r docker volume rm -f
                        docker network ls -q --filter type=custom | xargs -r docker network rm -f
                        docker builder prune --all --force
                        docker images -q | sort -u | grep -vE '^(node:22\\.10|node:22\\.10-slim)$' | xargs -r docker rmi -f
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                dir('ITE/GCL07/WSZ417391/Sprawozdanie2') {
                    sh 'docker build -f Dockerfile.build -t $IMAGE_BUILD .'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ITE/GCL07/WSZ417391/Sprawozdanie2') {
                    sh 'docker build -f Dockerfile.test -t $IMAGE_TEST .'
                    sh 'docker run --rm $IMAGE_TEST > test-${VERSION}.log'
                    archiveArtifacts artifacts: "test-${VERSION}.log", onlyIfSuccessful: true
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('ITE/GCL07/WSZ417391/Sprawozdanie2') {
                    sh '''
                        docker create --name temp-build-container $IMAGE_BUILD
                        docker cp temp-build-container:/node-js-dummy-test/node_modules ./node_modules
                        docker cp temp-build-container:/node-js-dummy-test/package.json .
                        docker cp temp-build-container:/node-js-dummy-test/src ./src
                        docker cp temp-build-container:/node-js-dummy-test/views ./views
                        docker rm temp-build-container
                        docker build -f Dockerfile.deploy -t $IMAGE_DEPLOY:$VERSION .
                    '''
                }
            }
        }

        stage('Publish') {
            steps {
                dir('ITE/GCL07/WSZ417391/Sprawozdanie2') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            docker run --rm -v $PWD:/app -w /app debian bash -c "apt-get update && apt-get install -y zip && zip -r ${ZIP_BASE}-${VERSION}.zip node_modules/ src/ views/ package.json"
                        '''
                        archiveArtifacts artifacts: "${ZIP_BASE}-${VERSION}.zip", onlyIfSuccessful: true

                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker tag $IMAGE_DEPLOY:$VERSION $IMAGE_TAG
                            docker push $IMAGE_TAG
                        '''
                    }
                }
            }
        }
    }
}
