FROM fedora:42

RUN dnf -y update && \ 
    dnf install -y install meson gcc glib2-devel ncurses-devel utf8proc-devel perl-ExtUtils*
RUN dnf -y install git
RUN git clone https://github.com/irssi/irssi.git
WORKDIR /irssi
RUN meson Build
RUN ninja -C Build