FROM python:3.7

RUN apt-get update && apt-get install -y \
    git \
    curl

RUN pip install pipenv

RUN git clone https://github.com/vguhesan/python-hello-world-with-unit-test ./pythonTest
WORKDIR /pythonTest