FROM fedora:latest

RUN dnf -y install git meson ninja-build \
    utf8proc-devel ncurses-devel gcc cmake \
    openssl-devel perl-ExtUtils* glib2-devel

RUN git clone https://github.com/irssi/irssi

WORKDIR /irssi

RUN meson Build