FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    git \
    rpm \
    tree \
    libncursesw5-dev \
    autotools-dev \
    automake \
    autoconf \
    build-essential

WORKDIR /app

RUN git clone https://github.com/htop-dev/htop .
RUN ./autogen.sh && ./configure && make && make install DESTDIR=/app/install
RUN tar -czvf htop.tar.gz -C /app/install .

COPY htop.spec .
RUN rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" htop.spec 