FROM ubuntu:22.04

# Instalacja zależności
RUN apt update && apt install -y git meson gcc pkg-config libglib2.0-dev libssl-dev libutf8proc-dev libncurses-dev perl

# Sklonowanie repozytorium Irssi
RUN git clone https://github.com/irssi/irssi.git
WORKDIR /irssi

RUN meson setup Build && meson compile -C Build
