FROM fedora:latest

RUN dnf install -y \
    git \
    gcc \
    meson \
    ninja-build \
    glib2-devel \
    openssl-devel \
    perl-devel \
    perl-ExtUtils-Embed \
    ncurses-devel 

WORKDIR /build

RUN git clone https://github.com/irssi/irssi.git

WORKDIR /build/irssi

RUN meson Build 
RUN ninja -C Build
