FROM debian:bullseye

WORKDIR /app

# skopiuj źródła
COPY xz/ ./

# zainstaluj narzędzia do testów
RUN apt-get update && apt-get install -y \
      build-essential autotools-dev autoconf automake libtool gettext pkg-config \
      ca-certificates

# przygotuj skrypt ENTRYPOINT, który uruchomi testy i zapisze logi
COPY test-entrypoint.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/test-entrypoint.sh

ENTRYPOINT ["test-entrypoint.sh"]
