FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    make \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y python3-poetry

ENV PATH="/root/.local/bin:${PATH}"

RUN apt-get update && apt-get install -y pipx && pipx install uv

RUN git clone https://github.com/pydantic/pytest-examples.git /app

WORKDIR /app

RUN make install
