pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    cleanWs()
                    sh 'docker system prune -af --volumes'
                }
            }
        }
        
        stage('Clone repo') {
            steps {
                sh "git clone -b MP416297 --single-branch https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git "
                sh "pwd"
                sh "ls"
            }
        }
        
        stage('Build') {
            steps{
                sh "docker build -t supertuxbld -f ./MDO2025_INO/ITE/GCL06/MP416297/Sprawozdanie2/supertux_dockerfiles/Dockerfile.bld ."
            }
        }
        
        stage('Test') {
            steps{
                sh "docker build -t supertuxtest -f ./MDO2025_INO/ITE/GCL06/MP416297/Sprawozdanie2/supertux_dockerfiles/Dockerfile.test ."
            }
        }
        
        stage('Deploy') {
            steps {
                sh "docker volume create supertux_build"
                sh "docker run -d --name supertux_build -v supertux_build:/supertux_build supertuxbld"
                sh "docker exec supertux_build cp supertux2 ../../supertux_build/"

                sh "docker run -d --name supertux_deploy -v supertux_build:/supertux_build ubuntu"
                sh "docker exec supertux_deploy cp supertux_build/supertux2 ."
                sh "docker exec supertux_deploy ./supertux2 --version"
            }
        }
        
        // stage('Publish') {
        //     steps {
        //         script {
        //             def artifactName = "supertux_deploy_${currentBuild.timestamp}.zip"
                    
        //             archiveArtifacts artifacts: artifactName, allowEmptyArchive: false
        //         }
        //     }
        // }
    }
}

