pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    cleanWs()
                    sh 'docker system prune -af --volumes'
                }
            }
        }
        
        stage('Clone repo') {
            steps {
                sh "git clone -b MP416297 --single-branch https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git "
                sh "pwd"
                sh "ls"
            }
        }
        
        stage('Build') {
            steps{
                sh "docker build -t supertuxbld -f ./MDO2025_INO/ITE/GCL06/MP416297/Sprawozdanie2/supertux_dockerfiles/Dockerfile.bld ."
            }
        }
        
        stage('Test') {
            steps{
                sh "docker build -t supertuxtest -f ./MDO2025_INO/ITE/GCL06/MP416297/Sprawozdanie2/supertux_dockerfiles/Dockerfile.test ."
            }
        }
        
        stage('Deploy') {
            steps {
                sh "docker volume create supertux_build"
                sh "docker run -v supertux_build:/supertux_build supertuxbld cp -r ../../supertux ../../supertux_build/supertux"
    

                sh "docker build -t main_container -f ./MDO2025_INO/ITE/GCL06/MP416297/Sprawozdanie2/supertux_dockerfiles/Dockerfile.maincontainer ."
                sh '''docker run -d -v supertux_build:/supertux_build main_container \
                            cp supertux_build . \
                            ./supertux/build/supertux2 --version
                '''
                // sh "docker exec supertux_deploy cp supertux_build/supertux2 ."
                // sh "docker exec supertux_deploy ./supertux2 --version"
            }
        }
        
        // stage('Publish') {
        //     steps {
        //         script {
        //             def artifactName = "supertux_deploy_${currentBuild.timestamp}.zip"
                    
        //             archiveArtifacts artifacts: artifactName, allowEmptyArchive: false
        //         }
        //     }
        // }
    }
}

