FROM node:22

RUN npm install -g pnpm

WORKDIR /app

RUN git clone https://github.com/CALLmeDOMIN/traffic_lights .

RUN pnpm install

RUN mkdir /volume_data

RUN cp -r /app/* /volume_data/

VOLUME /volume_data