FROM alpine:lastest@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
RUN apk add --no-cache git bash make clang libtool ncurses ncurses-dev
RUN git clone https://github.com/antirez/sds
WORKDIR /sds
RUN ["make"]