FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/

EXPOSE 80

LABEL maintainer="jakub.sadlowski@gmail.com"
LABEL version="1.0"
LABEL description="Nginx z własną konfiguracją"

CMD ["sh", "-c", "exit 1"]