FROM redis_build AS redis_test

WORKDIR /redis

RUN ./runtest --single unit/type/string --single unit/type/list \
  --tags "-slow -needs:save -needs:repl -external:skip -latency-monitor -needs:latency"