pipeline {
  agent {
    docker {
      image 'docker:20.10-dind'
      args  '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build image') {
      steps {
        // zmieniamy katalog roboczy na ten, w którym są Twoje Dockerfile’e
        dir('INO/GCL01/MG417201/lab3/dockerfiles') {
          sh 'docker build -t redis_build -f Dockerfile.build.redis .'
        }
      }
    }

    stage('Run tests') {
      steps {
        dir('INO/GCL01/MG417201/lab3/dockerfiles') {
          sh 'docker build -t redis_test -f Dockerfile.test.redis .'
        }
      }
    }
  }
}
