FROM fedora:42

RUN dnf -y install git meson gcc glib2-devel openssl-devel ncurses-devel utf8proc-devel perl-ExtUtils*

RUN git clone https://github.com/irssi/irssi

WORKDIR /irssi

RUN meson Build
RUN ninja -C Build