FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y git

WORKDIR /app                                                                       

RUN git clone https://github.com/InzynieriaOprogramowaniaAGH/MDO2025_INO.git 

CMD ["/bin/bash"]
